{% set name = "peakutils" %}
{% set version = "1.3.2" %}
{% set sha256 = "2cf1f609132f0219e2fc9c7e221b62d1c82c9a502ec9a4c1195823423275c954" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PeakUtils/PeakUtils-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.8
    - scipy >=0.14

test:
  imports:
    - {{ name }}

about:
  home: https://bitbucket.org/lucashnegri/peakutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Peak detection utilities for 1D data'

  description: |
    This package provides utilities related to the detection of peaks on 
    1D data. Includes functions to estimate baselines, finding the 
    indexes of peaks in the data and performing Gaussian fitting or centroid 
    computation to further increase the resolution of the peak detection.
  doc_url: http://pythonhosted.org/PeakUtils/
  dev_url: https://bitbucket.org/lucashnegri/peakutils/

extra:
  recipe-maintainers:
    - xmnlab
